use serialization types to avoid error messages
/usr/include/boost/serialization/access.hpp:116:11: error: ‘class boost::array<MiniDriverContainer, 15>’ has no member named ‘serialize’
         t.serialize(ar, file_version);
         ~~^~~~~~~~~
/usr/include/boost/serialization/access.hpp: In instantiation of ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_oarchive; T = boost::array<unsigned char, 14>]’:
/usr/include/boost/serialization/serialization.hpp:68:22:   required from ‘void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_oarchive; T = boost::array<unsigned char, 14>]’
/usr/include/boost/serialization/serialization.hpp:126:14:   required from ‘void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::text_oarchive; T = boost::array<unsigned char, 14>]’
/usr/include/boost/archive/detail/oserializer.hpp:153:40:   required from ‘void boost::archive::detail::oserializer<Archive, T>::save_object_data(boost::archive::detail::basic_oarchive&, const void*) const [with Archive = boost::archive::text_oarchive; T = boost::array<unsigned char, 14>]’
/usr/include/boost/archive/detail/oserializer.hpp:106:1:   required from ‘class boost::archive::detail::oserializer<boost::archive::text_oarchive, boost::array<unsigned char, 14> >’
/usr/include/boost/archive/detail/oserializer.hpp:258:13:   required from ‘static void boost::archive::detail::save_non_pointer_type<Archive>::save_standard::invoke(Archive&, const T&) [with T = boost::array<unsigned char, 14>; Archive = boost::archive::text_oarchive]’
/usr/include/boost/archive/detail/oserializer.hpp:315:22:   [ skipping 39 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/archive/detail/oserializer.hpp:315:22:   required from ‘static void boost::archive::detail::save_non_pointer_type<Archive>::invoke(Archive&, const T&) [with T = MiniDriver; Archive = boost::archive::text_oarchive]’
/usr/include/boost/archive/detail/oserializer.hpp:539:18:   required from ‘void boost::archive::save(Archive&, T&) [with Archive = boost::archive::text_oarchive; T = const MiniDriver]’
/usr/include/boost/archive/detail/common_oarchive.hpp:71:22:   required from ‘void boost::archive::detail::common_oarchive<Archive>::save_override(T&) [with T = const MiniDriver; Archive = boost::archive::text_oarchive]’
/usr/include/boost/archive/basic_text_oarchive.hpp:83:9:   required from ‘void boost::archive::basic_text_oarchive<Archive>::save_override(T&) [with T = const MiniDriver; Archive = boost::archive::text_oarchive]’
/usr/include/boost/archive/detail/interface_oarchive.hpp:70:9:   required from ‘Archive& boost::archive::detail::interface_oarchive<Archive>::operator<<(const T&) [with T = MiniDriver; Archive = boost::archive::text_oarchive]’
MiniDriver.cpp:182:15:   required from here
/usr/include/boost/serialization/access.hpp:116:11: error: ‘class boost::array<unsigned char, 14>’ has no member named ‘serialize’
/usr/include/boost/serialization/access.hpp: In instantiation of ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::array<MiniDriverContainer, 15>]’:
/usr/include/boost/serialization/serialization.hpp:68:22:   required from ‘void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::array<MiniDriverContainer, 15>]’
/usr/include/boost/serialization/serialization.hpp:126:14:   required from ‘void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::array<MiniDriverContainer, 15>]’
/usr/include/boost/archive/detail/iserializer.hpp:187:40:   required from ‘void boost::archive::detail::iserializer<Archive, T>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [with Archive = boost::archive::text_iarchive; T = boost::array<MiniDriverContainer, 15>]’
/usr/include/boost/archive/detail/iserializer.hpp:121:1:   required from ‘class boost::archive::detail::iserializer<boost::archive::text_iarchive, boost::array<MiniDriverContainer, 15> >’
/usr/include/boost/archive/detail/iserializer.hpp:409:13:   required from ‘static void boost::archive::detail::load_non_pointer_type<Archive>::load_standard::invoke(Archive&, const T&) [with T = boost::array<MiniDriverContainer, 15>; Archive = boost::archive::text_iarchive]’
/usr/include/boost/archive/detail/iserializer.hpp:461:22:   [ skipping 43 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/archive/detail/iserializer.hpp:624:18:   required from ‘void boost::archive::load(Archive&, T&) [with Archive = boost::archive::text_iarchive; T = MiniDriver]’
/usr/include/boost/archive/detail/common_iarchive.hpp:67:22:   required from ‘void boost::archive::detail::common_iarchive<Archive>::load_override(T&) [with T = MiniDriver; Archive = boost::archive::text_iarchive]’
/usr/include/boost/archive/basic_text_iarchive.hpp:70:9:   required from ‘void boost::archive::basic_text_iarchive<Archive>::load_override(T&) [with T = MiniDriver; Archive = boost::archive::text_iarchive]’
/usr/include/boost/archive/text_iarchive.hpp:82:52:   required from ‘void boost::archive::text_iarchive_impl<Archive>::load_override(T&) [with T = MiniDriver; Archive = boost::archive::text_iarchive]’
/usr/include/boost/archive/detail/interface_iarchive.hpp:68:9:   required from ‘Archive& boost::archive::detail::interface_iarchive<Archive>::operator>>(T&) [with T = MiniDriver; Archive = boost::archive::text_iarchive]’
MiniDriver.cpp:269:19:   required from here
/usr/include/boost/serialization/access.hpp:116:11: error: ‘class boost::array<MiniDriverContainer, 15>’ has no member named ‘serialize’
/usr/include/boost/serialization/access.hpp: In instantiation of ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::array<unsigned char, 14>]’:
/usr/include/boost/serialization/serialization.hpp:68:22:   required from ‘void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::array<unsigned char, 14>]’
/usr/include/boost/serialization/serialization.hpp:126:14:   required from ‘void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = boost::archive::text_iarchive; T = boost::array<unsigned char, 14>]’
/usr/include/boost/archive/detail/iserializer.hpp:187:40:   required from ‘void boost::archive::detail::iserializer<Archive, T>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [with Archive = boost::archive::text_iarchive; T = boost::array<unsigned char, 14>]’
/usr/include/boost/archive/detail/iserializer.hpp:121:1:   required from ‘class boost::archive::detail::iserializer<boost::archive::text_iarchive, boost::array<unsigned char, 14> >’
/usr/include/boost/archive/detail/iserializer.hpp:409:13:   required from ‘static void boost::archive::detail::load_non_pointer_type<Archive>::load_standard::invoke(Archive&, const T&) [with T = boost::array<unsigned char, 14>; Archive = boost::archive::text_iarchive]’
/usr/include/boost/archive/detail/iserializer.hpp:461:22:   [ skipping 43 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/archive/detail/iserializer.hpp:624:18:   required from ‘void boost::archive::load(Archive&, T&) [with Archive = boost::archive::text_iarchive; T = MiniDriver]’
/usr/include/boost/archive/detail/common_iarchive.hpp:67:22:   required from ‘void boost::archive::detail::common_iarchive<Archive>::load_override(T&) [with T = MiniDriver; Archive = boost::archive::text_iarchive]’
/usr/include/boost/archive/basic_text_iarchive.hpp:70:9:   required from ‘void boost::archive::basic_text_iarchive<Archive>::load_override(T&) [with T = MiniDriver; Archive = boost::archive::text_iarchive]’
/usr/include/boost/archive/text_iarchive.hpp:82:52:   required from ‘void boost::archive::text_iarchive_impl<Archive>::load_override(T&) [with T = MiniDriver; Archive = boost::archive::text_iarchive]’
/usr/include/boost/archive/detail/interface_iarchive.hpp:68:9:   required from ‘Archive& boost::archive::detail::interface_iarchive<Archive>::operator>>(T&) [with T = MiniDriver; Archive = boost::archive::text_iarchive]’
MiniDriver.cpp:269:19:   required from here
/usr/include/boost/serialization/access.hpp:116:11: error: ‘class boost::array<unsigned char, 14>’ has no member named ‘serialize’