Use std::array instead of boost::array
With boost 1.66.0 one keeps getting compiler errors
about undefined .serialize() method on boost arrays

/usr/local/include/boost/serialization/access.hpp:116:11:
error: no member named 'serialize' in
      'boost::array<MiniDriverContainer, 15>'
        t.serialize(ar, file_version);
        ~ ^